fireFerry/byob-bot

- main.py
Updated the messages to now have fancy embeds, changed $version to a more detailed $status, general cleanups & improvements on the code.
> Version 1.2

- main.py
Version 1.2.6 coming in with:
- A toggle for autorole!
- More support commands!
- a fully redesigned commands list!!
This update took me around 5h, but it was really worth the time 😄
See ya at the next one!
~fireFerry
> Version 1.2.6

- main.py
> Version 1.2.6.1

- main.py
> Version 1.2.6.2

- main.py
1/2 Update to version 1.2.7. Changelog will be in 2/2 update.
> Version 1.2.6.3

- main.py
2/2
This version includes:
- New made reaction role system, will be further updated as it's not that handy at the moment
- Fixed spelling errors
- dev-status command for the bot owner.
> Version 1.2.7

- main.py
- Full rewrite of reaction role system, works 100 times better now.
- Added support for staff to add joinable roles to users.
> Version 1.2.8

- main.py
Added back $joinrole and $leaverole, now using only the two captial letters:
- `$joinrole EH` will join the Ethical Hacker role.
> Version 1.2.8.1

- main.py
Small improvements to the reaction system.
> Version 1.2.8.3

- main.py
Small improvement to the reaction system. (Again)
> Version 1.2.8.4

- main.py
Reverted some changes in Reaction role system
> Version 1.2.8.5

- main.py
Fixed $addrole and $delrole command.
> Version 1.2.8.6

- main.py
- Added a @Notifications joinable role.
> Version 1.2.8.7

- main.py
Version 1.2.9 Providing:
- New member count system!
> Version 1.2.9

- main.py
- requirements.txt
Featuring:
- Fully working DM Ticket system!
- Close command for tickets
- Server Statistics
- Commands now work in dm!
> Version 2.0

- main.py
Mostly little grammatical things, doesn't change the functionality of the bot at all.
> Messages fix

- main.py
- requirements.txt
Bug fixes:
- fixed ticket system when the bot is in multiple servers.
Additions:
- Close button for tickets
- Buttons for links
> Version 2.0.1

- main.py
- requirements.txt
> Revert "Version 2.0.1"

- main.py
- requirements.txt
> Merge back "Version 2.0.1"

- main.py
Version 2.0.3:
Additions:
- Added function so people with Ticket Blacklist role can't create a new ticket.
Bug fixes:
- Fixed shutdown command,
> Version 2.0.3

- main.py
Version 2.0.4:
Bug fixes:
- Fixed issues when the bot is in multiple servers.
> Version 2.0.4
